name: Build Geode Mod

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Windows Mod
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Mod File
        uses: geode-sdk/build-geode-mod@main
        with:
          target: Windows
